version: "3.7"
services:
  app:
    build: .
    command: sleep infinity
    volumes:
      - ..:/original:cached
      - app:/app
      - ../.devcontainer:/app/.devcontainer:cached
      - home:/home/app
      - ~/.gitconfig:/home/app/.gitconfig:ro
      - ~/.zshrc:/home/app/.zshrc:ro
      - ~/.netrc:/home/app/.netrc:ro
volumes:
  app:
  home:
